---
apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsProvider
metadata:
  name: sample-provider
spec:
  providers:
  - matchLabels:
      "sops-private-key": "true"
  sops:
  - matchLabels:
      "sops-secret": "true"
---
apiVersion: addons.projectcapsule.dev/v1alpha1
kind: SopsProvider
metadata:
  name: namespace-provider
spec:
  providers:
  - namespaceSelector:
      matchLabels:
         "secrets": "sure"
  sops:
  - matchLabels:
      "sops-secret": "true"
