{{- if $.Values.rbac.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm.fullname" . }}-controller
  labels:
    {{- include "helm.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - "*"
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - "list"
    - "watch"
    - "get"
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - list
    - update
    - create
    - patch
- apiGroups:
  - "addons.projectcapsule.dev"
  resources:
  - "sopsproviders"
  - "sopsproviders/status"
  - "sopssecrets"
  - "sopssecrets/status"
  - "globalsopssecrets"
  - "globalsopssecrets/status"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm.fullname" . }}-controller
  labels:
    {{- include "helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "helm.fullname" . }}-controller
subjects:
  - name: {{ include "helm.serviceAccountName" . }}
    kind: ServiceAccount
    namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "helm.fullname" . }}
subjects:
  - name: {{ include "helm.serviceAccountName" . }}
    kind: ServiceAccount
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
