//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/peak-scale/sops-operator/internal/api"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSopsSecret) DeepCopyInto(out *GlobalSopsSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	if in.Sops != nil {
		in, out := &in.Sops, &out.Sops
		*out = new(api.Metadata)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSopsSecret.
func (in *GlobalSopsSecret) DeepCopy() *GlobalSopsSecret {
	if in == nil {
		return nil
	}
	out := new(GlobalSopsSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalSopsSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSopsSecretItem) DeepCopyInto(out *GlobalSopsSecretItem) {
	*out = *in
	in.SopsSecretItem.DeepCopyInto(&out.SopsSecretItem)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSopsSecretItem.
func (in *GlobalSopsSecretItem) DeepCopy() *GlobalSopsSecretItem {
	if in == nil {
		return nil
	}
	out := new(GlobalSopsSecretItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSopsSecretList) DeepCopyInto(out *GlobalSopsSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GlobalSopsSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSopsSecretList.
func (in *GlobalSopsSecretList) DeepCopy() *GlobalSopsSecretList {
	if in == nil {
		return nil
	}
	out := new(GlobalSopsSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalSopsSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSopsSecretSpec) DeepCopyInto(out *GlobalSopsSecretSpec) {
	*out = *in
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]*GlobalSopsSecretItem, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(GlobalSopsSecretItem)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSopsSecretSpec.
func (in *GlobalSopsSecretSpec) DeepCopy() *GlobalSopsSecretSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalSopsSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsProvider) DeepCopyInto(out *SopsProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsProvider.
func (in *SopsProvider) DeepCopy() *SopsProvider {
	if in == nil {
		return nil
	}
	out := new(SopsProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SopsProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsProviderItemStatus) DeepCopyInto(out *SopsProviderItemStatus) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
	out.Origin = in.Origin
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsProviderItemStatus.
func (in *SopsProviderItemStatus) DeepCopy() *SopsProviderItemStatus {
	if in == nil {
		return nil
	}
	out := new(SopsProviderItemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsProviderList) DeepCopyInto(out *SopsProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SopsProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsProviderList.
func (in *SopsProviderList) DeepCopy() *SopsProviderList {
	if in == nil {
		return nil
	}
	out := new(SopsProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SopsProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsProviderSpec) DeepCopyInto(out *SopsProviderSpec) {
	*out = *in
	if in.SOPSSelectors != nil {
		in, out := &in.SOPSSelectors, &out.SOPSSelectors
		*out = make([]*api.NamespacedSelector, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(api.NamespacedSelector)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ProviderSecrets != nil {
		in, out := &in.ProviderSecrets, &out.ProviderSecrets
		*out = make([]*api.NamespacedSelector, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(api.NamespacedSelector)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsProviderSpec.
func (in *SopsProviderSpec) DeepCopy() *SopsProviderSpec {
	if in == nil {
		return nil
	}
	out := new(SopsProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsProviderStatus) DeepCopyInto(out *SopsProviderStatus) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]*SopsProviderItemStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SopsProviderItemStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	in.Condition.DeepCopyInto(&out.Condition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsProviderStatus.
func (in *SopsProviderStatus) DeepCopy() *SopsProviderStatus {
	if in == nil {
		return nil
	}
	out := new(SopsProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsSecret) DeepCopyInto(out *SopsSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	if in.Sops != nil {
		in, out := &in.Sops, &out.Sops
		*out = new(api.Metadata)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsSecret.
func (in *SopsSecret) DeepCopy() *SopsSecret {
	if in == nil {
		return nil
	}
	out := new(SopsSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SopsSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsSecretItem) DeepCopyInto(out *SopsSecretItem) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.StringData != nil {
		in, out := &in.StringData, &out.StringData
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Immutable != nil {
		in, out := &in.Immutable, &out.Immutable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsSecretItem.
func (in *SopsSecretItem) DeepCopy() *SopsSecretItem {
	if in == nil {
		return nil
	}
	out := new(SopsSecretItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsSecretItemStatus) DeepCopyInto(out *SopsSecretItemStatus) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsSecretItemStatus.
func (in *SopsSecretItemStatus) DeepCopy() *SopsSecretItemStatus {
	if in == nil {
		return nil
	}
	out := new(SopsSecretItemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsSecretList) DeepCopyInto(out *SopsSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SopsSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsSecretList.
func (in *SopsSecretList) DeepCopy() *SopsSecretList {
	if in == nil {
		return nil
	}
	out := new(SopsSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SopsSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsSecretSpec) DeepCopyInto(out *SopsSecretSpec) {
	*out = *in
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]*SopsSecretItem, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SopsSecretItem)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsSecretSpec.
func (in *SopsSecretSpec) DeepCopy() *SopsSecretSpec {
	if in == nil {
		return nil
	}
	out := new(SopsSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SopsSecretStatus) DeepCopyInto(out *SopsSecretStatus) {
	*out = *in
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]*SopsSecretItemStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SopsSecretItemStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	in.Condition.DeepCopyInto(&out.Condition)
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]*api.Origin, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(api.Origin)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SopsSecretStatus.
func (in *SopsSecretStatus) DeepCopy() *SopsSecretStatus {
	if in == nil {
		return nil
	}
	out := new(SopsSecretStatus)
	in.DeepCopyInto(out)
	return out
}
