name: Test charts
permissions: {}

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/helm-*.yml'
      - 'api/**'
      - 'cmd/**'
      - 'internal/**'
      - 'e2e/*'
      - '.ko.yaml'
      - 'go.*'
      - 'main.go'
      - 'Makefile'
jobs:
  linter-artifacthub:
    runs-on: ubuntu-latest
    container:
      image: artifacthub/ah
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run ah lint
        working-directory: ./charts/
        run: ah lint
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4
      - name: Setup Chart Linting
        id: lint
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/configs/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        run: ct lint --debug --config .github/configs/ct.yaml --lint-conf .github/configs/lintconf.yaml

      - name: Run docs-testing (helm-docs)
        id: helm-docs
        run: |
          make helm-docs
          if [[ $(git diff --stat) != '' ]]; then
            echo -e '\033[0;31mDocumentation outdated! (Run make helm-docs locally and commit)\033[0m ❌'
            git diff --color
            exit 1
          else
            echo -e '\033[0;32mDocumentation up to date\033[0m ✔'
          fi
      - name: Run schema-testing (helm-schema)
        id: helm-schema
        run: |
          make helm-schema
          if [[ $(git diff --stat) != '' ]]; then
            echo -e '\033[0;31mSchema outdated! (Run make helm-schema locally and commit)\033[0m ❌'
            git diff --color
            exit 1
          else
            echo -e '\033[0;32mSchema up to date\033[0m ✔'
          fi
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@cfd369df47bac1f9d620234261996ed06b5a1c19
        with:
            version: 'latest'
      - name: Run chart-testing (install)
        run: make helm-test
        if: steps.list-changed.outputs.changed == 'true'
